### PR TITLE
feat: add default lang and global scope plugin options for SFC `i18n` custom block

### LINKED ISSUE #108: feat: add default `lang` and `scope` on plugin configuration for `i18n` custom block
**Is your feature request related to a problem?**

It is not a problem, it is a new feature.

**Describe the solution you'd like**

When using `i18n` custom block resources inside the `sfc` components, it is a pain writing `global` and `lang` attributes: provide a way on plugin configuration to specify default `scope` and `lang`.

When using `i18n` with `src` external resource, it is also a pain to add `global` scope.

With these options added to plugin configuration, we have to write less code on each `sfc` component.

Also, the plugin should override default ones if provided on `i18n` custom block. 

This feature shoundn't be present when using `src` attribute of `i18n` custom block: only `scope`.

You can see an example for `lang` on `vite-plugin-pages` repo for `route lang` attribute (`route` is also a custom block similar to `i18n`).

**Describe alternatives you've considered**

I have no consider alternatives, should be on this plugin.

**Additional context**

No more context required.

### PR DESCRIPTION
**Pull request by userquin**
closes #108 

Also added .idea/ directory to be excluded on .gitignore (intellj/webstorm stuff).

### CODE REVIEW

**Comment by userquin** [comment]
Maybe options names can be others...

**Comment by kazupon** [comment]
@userquin 
Thank you for your PR!

Sorry, currently, I'm a little busy with my day job. 🙇 
I'll try to check your PR later. 😉

**Comment by userquin** [comment]
I need to add docs for these 2 new options (but first I'll wait for your feedback, once ok I can add docs) and also on the site (at least here: https://vue-i18n.intlify.dev/guide/advanced/sfc.html#bundling-with-vite, but it is is another repo).

**Comment by kazupon** [comment]
@userquin 
I've just checked your PR!

Could you add these options docs to [README](https://github.com/intlify/vite-plugin-vue-i18n#wrench-options) please?

**Comment by userquin** [comment]
> 
> 
> @userquin
> I've just checked your PR!
> 
> Could you add these options docs to [README](https://github.com/intlify/vite-plugin-vue-i18n#wrench-options) please?

give me a few minutes

**Comment by userquin** [comment]
I only add on options section (with n example), do you want I add something on `i18n` custom block section?

**Comment by userquin** [comment]
Don't merge yet.

I'll add a warning, since `globalSFCScope` cannot be disable once configured (`global` attribute has no values).

For `defaultSFCLang` I need to add a hint: it can be overriden using `i18n lang` custom block attribute.

**Comment by userquin** [comment]
Done

**Comment by kazupon** [comment]
@userquin 
That's great work!
Thanks!

**Pull request merged**
